spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  datasource:
    ds1:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test
      username: sa
      password:
    ds2:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/dsdb?useSSL=false
      username: dsinterface
      password: dslhxf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

nas:
  path: /Users/zhangyin/code/other/rawa-cloud-app/nas

app:
  office-host: localhost:3000
  temp: /Users/zhangyin/code/other/rawa-cloud-app/temp
  import-path: /Users/zhangyin/code/other/rawa-cloud-app/imports
  export-path: /Users/zhangyin/code/other/rawa-cloud-app/exports
  sync-cron: 0 50 1 * * ?
