spring:
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rawa-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
    ds2:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/dsdb?useSSL=false
      username: dsinterface
      password: dslhxf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

nas:
  path: /Users/zhangyin/nas

app:
  office-host: localhost:3000
  temp: /Users/zhangyin/IdeaProjects/rawa-cloud-app/temp
  import-path: /Users/zhangyin/IdeaProjects/rawa-cloud-app/imports
  export-path: /Users/zhangyin/IdeaProjects/rawa-cloud-app/exports
  sync-cron: 0 50 1 * * ?
