spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    open-in-view: true
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8

jodconverter:
  enabled: true
#  office-home: C:\\Program Files (x86)\\OpenOffice 4
  office-home: /Applications/OpenOffice.app/Contents
  max-tasks-per-process: 10
  port-numbers: 8100

