spring:
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rawa-db:3306/rawa-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
      username: app_admin
      password: 123456
    ds2:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://10.148.30.127:8110/dsdb?useSSL=false
      username: dsinterface
      password: dslhxf
  jpa:
    hibernate:
      ddl-auto: update

nas:
  path: /nas

app:
  office-host: rawa-office
  temp: /temp
  import-path: /imports
  export-path: /exports
  sync-cron: 0 0/30 * * * ?